### PR TITLE
Suppress file_get_contents() warning

### PR DESCRIPTION
**Pull request by zubfatal**
Suppressed file_get_contents() warning, since we're throwing an exception anyways, if the request fails.

### CODE REVIEW

**Comment by zubfatal** [comment]
Kind of unrelated, and I'm not sure how it works, but I'm working on a project which uses this API client through composer - when are changes made to this repository pushed onto packagist.org ?

**Comment by nikhil88877** [comment]
> Kind of unrelated, and I'm not sure how it works, but I'm working on a project which uses this API client through composer - when are changes made to this repository pushed onto packagist.org ?

@zubfatal I have pushed the latest version(**1.0.2**) on the Packagist. You should be able to pull the latest version through composer. I'm new to PHP, so thanks again for raising the PR and improving the repository. Please flag us in case you find any more issue(s)

**Comment by zubfatal** [comment]
@nikhil88877 Thanks! I can confirm it works when updating to 1.0.2 with composer.

I'm not sure, but when you say `flag us` - should I contact you in a different manor rather than updating my fork and send you a PR?

**Comment by nikhil88877** [comment]
@zubfatal  We will appreciate if you raise the PR similar to what you have done in the past.

**Pull request merged**
